// Code generated by protoc-gen-go. DO NOT EDIT.
// source: files.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FileMeta struct {
	Filename             string   `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Length               string   `protobuf:"bytes,2,opt,name=length,proto3" json:"length,omitempty"`
	Sha256               string   `protobuf:"bytes,3,opt,name=sha256,proto3" json:"sha256,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileMeta) Reset()         { *m = FileMeta{} }
func (m *FileMeta) String() string { return proto.CompactTextString(m) }
func (*FileMeta) ProtoMessage()    {}
func (*FileMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_cac8f32ecfdd343c, []int{0}
}

func (m *FileMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileMeta.Unmarshal(m, b)
}
func (m *FileMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileMeta.Marshal(b, m, deterministic)
}
func (m *FileMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileMeta.Merge(m, src)
}
func (m *FileMeta) XXX_Size() int {
	return xxx_messageInfo_FileMeta.Size(m)
}
func (m *FileMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_FileMeta.DiscardUnknown(m)
}

var xxx_messageInfo_FileMeta proto.InternalMessageInfo

func (m *FileMeta) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

func (m *FileMeta) GetLength() string {
	if m != nil {
		return m.Length
	}
	return ""
}

func (m *FileMeta) GetSha256() string {
	if m != nil {
		return m.Sha256
	}
	return ""
}

type File struct {
	Filename             string    `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Meta                 *FileMeta `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *File) Reset()         { *m = File{} }
func (m *File) String() string { return proto.CompactTextString(m) }
func (*File) ProtoMessage()    {}
func (*File) Descriptor() ([]byte, []int) {
	return fileDescriptor_cac8f32ecfdd343c, []int{1}
}

func (m *File) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_File.Unmarshal(m, b)
}
func (m *File) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_File.Marshal(b, m, deterministic)
}
func (m *File) XXX_Merge(src proto.Message) {
	xxx_messageInfo_File.Merge(m, src)
}
func (m *File) XXX_Size() int {
	return xxx_messageInfo_File.Size(m)
}
func (m *File) XXX_DiscardUnknown() {
	xxx_messageInfo_File.DiscardUnknown(m)
}

var xxx_messageInfo_File proto.InternalMessageInfo

func (m *File) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

func (m *File) GetMeta() *FileMeta {
	if m != nil {
		return m.Meta
	}
	return nil
}

type Directory struct {
	DirectoryName        string   `protobuf:"bytes,1,opt,name=directory_name,json=directoryName,proto3" json:"directory_name,omitempty"`
	File                 []string `protobuf:"bytes,2,rep,name=File,proto3" json:"File,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Directory) Reset()         { *m = Directory{} }
func (m *Directory) String() string { return proto.CompactTextString(m) }
func (*Directory) ProtoMessage()    {}
func (*Directory) Descriptor() ([]byte, []int) {
	return fileDescriptor_cac8f32ecfdd343c, []int{2}
}

func (m *Directory) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Directory.Unmarshal(m, b)
}
func (m *Directory) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Directory.Marshal(b, m, deterministic)
}
func (m *Directory) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Directory.Merge(m, src)
}
func (m *Directory) XXX_Size() int {
	return xxx_messageInfo_Directory.Size(m)
}
func (m *Directory) XXX_DiscardUnknown() {
	xxx_messageInfo_Directory.DiscardUnknown(m)
}

var xxx_messageInfo_Directory proto.InternalMessageInfo

func (m *Directory) GetDirectoryName() string {
	if m != nil {
		return m.DirectoryName
	}
	return ""
}

func (m *Directory) GetFile() []string {
	if m != nil {
		return m.File
	}
	return nil
}

// CreateFileSpace
type CreateFileSpaceRequest struct {
	SpaceName            string   `protobuf:"bytes,1,opt,name=space_name,json=spaceName,proto3" json:"space_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateFileSpaceRequest) Reset()         { *m = CreateFileSpaceRequest{} }
func (m *CreateFileSpaceRequest) String() string { return proto.CompactTextString(m) }
func (*CreateFileSpaceRequest) ProtoMessage()    {}
func (*CreateFileSpaceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cac8f32ecfdd343c, []int{3}
}

func (m *CreateFileSpaceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateFileSpaceRequest.Unmarshal(m, b)
}
func (m *CreateFileSpaceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateFileSpaceRequest.Marshal(b, m, deterministic)
}
func (m *CreateFileSpaceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateFileSpaceRequest.Merge(m, src)
}
func (m *CreateFileSpaceRequest) XXX_Size() int {
	return xxx_messageInfo_CreateFileSpaceRequest.Size(m)
}
func (m *CreateFileSpaceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateFileSpaceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateFileSpaceRequest proto.InternalMessageInfo

func (m *CreateFileSpaceRequest) GetSpaceName() string {
	if m != nil {
		return m.SpaceName
	}
	return ""
}

type CreateFileSpaceResponse struct {
	Status               Status   `protobuf:"varint,1,opt,name=status,proto3,enum=Status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateFileSpaceResponse) Reset()         { *m = CreateFileSpaceResponse{} }
func (m *CreateFileSpaceResponse) String() string { return proto.CompactTextString(m) }
func (*CreateFileSpaceResponse) ProtoMessage()    {}
func (*CreateFileSpaceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cac8f32ecfdd343c, []int{4}
}

func (m *CreateFileSpaceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateFileSpaceResponse.Unmarshal(m, b)
}
func (m *CreateFileSpaceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateFileSpaceResponse.Marshal(b, m, deterministic)
}
func (m *CreateFileSpaceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateFileSpaceResponse.Merge(m, src)
}
func (m *CreateFileSpaceResponse) XXX_Size() int {
	return xxx_messageInfo_CreateFileSpaceResponse.Size(m)
}
func (m *CreateFileSpaceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateFileSpaceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateFileSpaceResponse proto.InternalMessageInfo

func (m *CreateFileSpaceResponse) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return Status_success
}

// CheckFileSpaceExists
type FetchFileSpaceRequest struct {
	SpaceName            string   `protobuf:"bytes,1,opt,name=space_name,json=spaceName,proto3" json:"space_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FetchFileSpaceRequest) Reset()         { *m = FetchFileSpaceRequest{} }
func (m *FetchFileSpaceRequest) String() string { return proto.CompactTextString(m) }
func (*FetchFileSpaceRequest) ProtoMessage()    {}
func (*FetchFileSpaceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cac8f32ecfdd343c, []int{5}
}

func (m *FetchFileSpaceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FetchFileSpaceRequest.Unmarshal(m, b)
}
func (m *FetchFileSpaceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FetchFileSpaceRequest.Marshal(b, m, deterministic)
}
func (m *FetchFileSpaceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FetchFileSpaceRequest.Merge(m, src)
}
func (m *FetchFileSpaceRequest) XXX_Size() int {
	return xxx_messageInfo_FetchFileSpaceRequest.Size(m)
}
func (m *FetchFileSpaceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FetchFileSpaceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FetchFileSpaceRequest proto.InternalMessageInfo

func (m *FetchFileSpaceRequest) GetSpaceName() string {
	if m != nil {
		return m.SpaceName
	}
	return ""
}

type FetchFileSpaceResponse struct {
	Exist                bool     `protobuf:"varint,1,opt,name=exist,proto3" json:"exist,omitempty"`
	PrevFileSpace        string   `protobuf:"bytes,2,opt,name=prev_file_space,json=prevFileSpace,proto3" json:"prev_file_space,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FetchFileSpaceResponse) Reset()         { *m = FetchFileSpaceResponse{} }
func (m *FetchFileSpaceResponse) String() string { return proto.CompactTextString(m) }
func (*FetchFileSpaceResponse) ProtoMessage()    {}
func (*FetchFileSpaceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cac8f32ecfdd343c, []int{6}
}

func (m *FetchFileSpaceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FetchFileSpaceResponse.Unmarshal(m, b)
}
func (m *FetchFileSpaceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FetchFileSpaceResponse.Marshal(b, m, deterministic)
}
func (m *FetchFileSpaceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FetchFileSpaceResponse.Merge(m, src)
}
func (m *FetchFileSpaceResponse) XXX_Size() int {
	return xxx_messageInfo_FetchFileSpaceResponse.Size(m)
}
func (m *FetchFileSpaceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FetchFileSpaceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FetchFileSpaceResponse proto.InternalMessageInfo

func (m *FetchFileSpaceResponse) GetExist() bool {
	if m != nil {
		return m.Exist
	}
	return false
}

func (m *FetchFileSpaceResponse) GetPrevFileSpace() string {
	if m != nil {
		return m.PrevFileSpace
	}
	return ""
}

func init() {
	proto.RegisterType((*FileMeta)(nil), "FileMeta")
	proto.RegisterType((*File)(nil), "File")
	proto.RegisterType((*Directory)(nil), "Directory")
	proto.RegisterType((*CreateFileSpaceRequest)(nil), "CreateFileSpaceRequest")
	proto.RegisterType((*CreateFileSpaceResponse)(nil), "CreateFileSpaceResponse")
	proto.RegisterType((*FetchFileSpaceRequest)(nil), "FetchFileSpaceRequest")
	proto.RegisterType((*FetchFileSpaceResponse)(nil), "FetchFileSpaceResponse")
}

func init() {
	proto.RegisterFile("files.proto", fileDescriptor_cac8f32ecfdd343c)
}

var fileDescriptor_cac8f32ecfdd343c = []byte{
	// 318 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0xcd, 0x6b, 0xb3, 0x40,
	0x10, 0x87, 0xc9, 0x97, 0xd1, 0xc9, 0x9b, 0x04, 0x96, 0xb7, 0x46, 0x84, 0xd0, 0xb0, 0xd0, 0x92,
	0x93, 0x07, 0x4b, 0x53, 0xe8, 0xad, 0x6d, 0xf0, 0x96, 0x1e, 0x36, 0x90, 0x43, 0x2f, 0xb2, 0xb5,
	0xd3, 0x2a, 0x18, 0xb5, 0xee, 0xa6, 0xb4, 0xff, 0x7d, 0xd9, 0xd5, 0x48, 0x48, 0x3f, 0xa0, 0x27,
	0x7d, 0x7e, 0x3a, 0xcf, 0x38, 0xe3, 0xc2, 0xe0, 0x39, 0x49, 0x51, 0x78, 0x45, 0x99, 0xcb, 0xdc,
	0xfd, 0x27, 0x24, 0x97, 0xbb, 0x9a, 0xe8, 0x06, 0xcc, 0x20, 0x49, 0x71, 0x85, 0x92, 0x13, 0x17,
	0x4c, 0xf5, 0x62, 0xc6, 0xb7, 0xe8, 0xb4, 0x66, 0xad, 0xb9, 0xc5, 0x1a, 0x26, 0x36, 0x18, 0x29,
	0x66, 0x2f, 0x32, 0x76, 0xda, 0xfa, 0x49, 0x4d, 0x2a, 0x17, 0x31, 0xf7, 0x2f, 0x17, 0x4e, 0xa7,
	0xca, 0x2b, 0xa2, 0x37, 0xd0, 0x55, 0xde, 0x5f, 0x9d, 0x53, 0xe8, 0x6e, 0x51, 0x72, 0x6d, 0x1c,
	0xf8, 0x96, 0xb7, 0xff, 0x10, 0xa6, 0x63, 0x1a, 0x80, 0xb5, 0x4c, 0x4a, 0x8c, 0x64, 0x5e, 0x7e,
	0x90, 0x33, 0x18, 0x3d, 0xed, 0x21, 0x3c, 0xb0, 0x0d, 0x9b, 0xf4, 0x5e, 0x29, 0x49, 0xd5, 0xd6,
	0x69, 0xcf, 0x3a, 0x73, 0x8b, 0xe9, 0x7b, 0x7a, 0x05, 0xf6, 0x5d, 0x89, 0x5c, 0xa2, 0xa2, 0x75,
	0xc1, 0x23, 0x64, 0xf8, 0xba, 0x43, 0x21, 0xc9, 0x14, 0x40, 0x28, 0x3e, 0x14, 0x5a, 0x3a, 0x51,
	0x32, 0x7a, 0x0d, 0x93, 0x2f, 0x85, 0xa2, 0xc8, 0x33, 0x81, 0xe4, 0x14, 0x8c, 0x6a, 0x8d, 0xba,
	0x6a, 0xe4, 0xf7, 0xbd, 0xb5, 0x46, 0x56, 0xc7, 0x74, 0x01, 0x27, 0x01, 0xca, 0x28, 0xfe, 0x6b,
	0xcf, 0x0d, 0xd8, 0xc7, 0x75, 0x75, 0xcb, 0xff, 0xd0, 0xc3, 0xf7, 0x44, 0x48, 0x5d, 0x63, 0xb2,
	0x0a, 0xc8, 0x39, 0x8c, 0x8b, 0x12, 0xdf, 0x42, 0xb5, 0xd4, 0x50, 0x6b, 0xea, 0x1f, 0x34, 0x54,
	0x71, 0x63, 0xf1, 0x57, 0xd0, 0x53, 0x20, 0xc8, 0x12, 0xc6, 0x47, 0x43, 0x91, 0x89, 0xf7, 0xfd,
	0x7e, 0x5c, 0xc7, 0xfb, 0x61, 0xfe, 0xdb, 0xfe, 0x43, 0x4f, 0x9f, 0x9f, 0x47, 0x43, 0x5f, 0x2e,
	0x3e, 0x03, 0x00, 0x00, 0xff, 0xff, 0xde, 0xf1, 0x6d, 0xe2, 0x63, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// FilesClient is the client API for Files service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FilesClient interface {
	CreateFileSpace(ctx context.Context, in *CreateFileSpaceRequest, opts ...grpc.CallOption) (*CreateFileSpaceResponse, error)
}

type filesClient struct {
	cc grpc.ClientConnInterface
}

func NewFilesClient(cc grpc.ClientConnInterface) FilesClient {
	return &filesClient{cc}
}

func (c *filesClient) CreateFileSpace(ctx context.Context, in *CreateFileSpaceRequest, opts ...grpc.CallOption) (*CreateFileSpaceResponse, error) {
	out := new(CreateFileSpaceResponse)
	err := c.cc.Invoke(ctx, "/Files/CreateFileSpace", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FilesServer is the server API for Files service.
type FilesServer interface {
	CreateFileSpace(context.Context, *CreateFileSpaceRequest) (*CreateFileSpaceResponse, error)
}

// UnimplementedFilesServer can be embedded to have forward compatible implementations.
type UnimplementedFilesServer struct {
}

func (*UnimplementedFilesServer) CreateFileSpace(ctx context.Context, req *CreateFileSpaceRequest) (*CreateFileSpaceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateFileSpace not implemented")
}

func RegisterFilesServer(s *grpc.Server, srv FilesServer) {
	s.RegisterService(&_Files_serviceDesc, srv)
}

func _Files_CreateFileSpace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateFileSpaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FilesServer).CreateFileSpace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Files/CreateFileSpace",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FilesServer).CreateFileSpace(ctx, req.(*CreateFileSpaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Files_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Files",
	HandlerType: (*FilesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateFileSpace",
			Handler:    _Files_CreateFileSpace_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "files.proto",
}
