// Code generated by protoc-gen-go. DO NOT EDIT.
// source: problems.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateProblemRequest struct {
	Problem              *Problem `protobuf:"bytes,1,opt,name=problem,proto3" json:"problem,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateProblemRequest) Reset()         { *m = CreateProblemRequest{} }
func (m *CreateProblemRequest) String() string { return proto.CompactTextString(m) }
func (*CreateProblemRequest) ProtoMessage()    {}
func (*CreateProblemRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_11c986fb2f668273, []int{0}
}

func (m *CreateProblemRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateProblemRequest.Unmarshal(m, b)
}
func (m *CreateProblemRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateProblemRequest.Marshal(b, m, deterministic)
}
func (m *CreateProblemRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateProblemRequest.Merge(m, src)
}
func (m *CreateProblemRequest) XXX_Size() int {
	return xxx_messageInfo_CreateProblemRequest.Size(m)
}
func (m *CreateProblemRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateProblemRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateProblemRequest proto.InternalMessageInfo

func (m *CreateProblemRequest) GetProblem() *Problem {
	if m != nil {
		return m.Problem
	}
	return nil
}

type CreateProblemResponse struct {
	Status               Status   `protobuf:"varint,1,opt,name=status,proto3,enum=Status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateProblemResponse) Reset()         { *m = CreateProblemResponse{} }
func (m *CreateProblemResponse) String() string { return proto.CompactTextString(m) }
func (*CreateProblemResponse) ProtoMessage()    {}
func (*CreateProblemResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_11c986fb2f668273, []int{1}
}

func (m *CreateProblemResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateProblemResponse.Unmarshal(m, b)
}
func (m *CreateProblemResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateProblemResponse.Marshal(b, m, deterministic)
}
func (m *CreateProblemResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateProblemResponse.Merge(m, src)
}
func (m *CreateProblemResponse) XXX_Size() int {
	return xxx_messageInfo_CreateProblemResponse.Size(m)
}
func (m *CreateProblemResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateProblemResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateProblemResponse proto.InternalMessageInfo

func (m *CreateProblemResponse) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return Status_success
}

type FetechProblemRequest struct {
	Pid                  uint64   `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FetechProblemRequest) Reset()         { *m = FetechProblemRequest{} }
func (m *FetechProblemRequest) String() string { return proto.CompactTextString(m) }
func (*FetechProblemRequest) ProtoMessage()    {}
func (*FetechProblemRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_11c986fb2f668273, []int{2}
}

func (m *FetechProblemRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FetechProblemRequest.Unmarshal(m, b)
}
func (m *FetechProblemRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FetechProblemRequest.Marshal(b, m, deterministic)
}
func (m *FetechProblemRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FetechProblemRequest.Merge(m, src)
}
func (m *FetechProblemRequest) XXX_Size() int {
	return xxx_messageInfo_FetechProblemRequest.Size(m)
}
func (m *FetechProblemRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FetechProblemRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FetechProblemRequest proto.InternalMessageInfo

func (m *FetechProblemRequest) GetPid() uint64 {
	if m != nil {
		return m.Pid
	}
	return 0
}

type FetchProblemResponse struct {
	Problem              *Problem `protobuf:"bytes,1,opt,name=problem,proto3" json:"problem,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FetchProblemResponse) Reset()         { *m = FetchProblemResponse{} }
func (m *FetchProblemResponse) String() string { return proto.CompactTextString(m) }
func (*FetchProblemResponse) ProtoMessage()    {}
func (*FetchProblemResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_11c986fb2f668273, []int{3}
}

func (m *FetchProblemResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FetchProblemResponse.Unmarshal(m, b)
}
func (m *FetchProblemResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FetchProblemResponse.Marshal(b, m, deterministic)
}
func (m *FetchProblemResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FetchProblemResponse.Merge(m, src)
}
func (m *FetchProblemResponse) XXX_Size() int {
	return xxx_messageInfo_FetchProblemResponse.Size(m)
}
func (m *FetchProblemResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FetchProblemResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FetchProblemResponse proto.InternalMessageInfo

func (m *FetchProblemResponse) GetProblem() *Problem {
	if m != nil {
		return m.Problem
	}
	return nil
}

type Problem struct {
	Pid                  uint64   `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	TimeLimit            uint64   `protobuf:"varint,3,opt,name=time_limit,json=timeLimit,proto3" json:"time_limit,omitempty"`
	MemoryLimit          uint64   `protobuf:"varint,4,opt,name=memory_limit,json=memoryLimit,proto3" json:"memory_limit,omitempty"`
	Description          string   `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	InputFormat          string   `protobuf:"bytes,6,opt,name=input_format,json=inputFormat,proto3" json:"input_format,omitempty"`
	OutputFormat         string   `protobuf:"bytes,7,opt,name=output_format,json=outputFormat,proto3" json:"output_format,omitempty"`
	Example              string   `protobuf:"bytes,8,opt,name=example,proto3" json:"example,omitempty"`
	HintAndLimit         string   `protobuf:"bytes,9,opt,name=hint_and_limit,json=hintAndLimit,proto3" json:"hint_and_limit,omitempty"`
	PublicizerId         uint64   `protobuf:"varint,10,opt,name=publicizer_id,json=publicizerId,proto3" json:"publicizer_id,omitempty"`
	FileIoInputName      string   `protobuf:"bytes,11,opt,name=file_io_input_name,json=fileIoInputName,proto3" json:"file_io_input_name,omitempty"`
	FileIoOutputName     string   `protobuf:"bytes,12,opt,name=file_io_output_name,json=fileIoOutputName,proto3" json:"file_io_output_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Problem) Reset()         { *m = Problem{} }
func (m *Problem) String() string { return proto.CompactTextString(m) }
func (*Problem) ProtoMessage()    {}
func (*Problem) Descriptor() ([]byte, []int) {
	return fileDescriptor_11c986fb2f668273, []int{4}
}

func (m *Problem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Problem.Unmarshal(m, b)
}
func (m *Problem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Problem.Marshal(b, m, deterministic)
}
func (m *Problem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Problem.Merge(m, src)
}
func (m *Problem) XXX_Size() int {
	return xxx_messageInfo_Problem.Size(m)
}
func (m *Problem) XXX_DiscardUnknown() {
	xxx_messageInfo_Problem.DiscardUnknown(m)
}

var xxx_messageInfo_Problem proto.InternalMessageInfo

func (m *Problem) GetPid() uint64 {
	if m != nil {
		return m.Pid
	}
	return 0
}

func (m *Problem) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Problem) GetTimeLimit() uint64 {
	if m != nil {
		return m.TimeLimit
	}
	return 0
}

func (m *Problem) GetMemoryLimit() uint64 {
	if m != nil {
		return m.MemoryLimit
	}
	return 0
}

func (m *Problem) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Problem) GetInputFormat() string {
	if m != nil {
		return m.InputFormat
	}
	return ""
}

func (m *Problem) GetOutputFormat() string {
	if m != nil {
		return m.OutputFormat
	}
	return ""
}

func (m *Problem) GetExample() string {
	if m != nil {
		return m.Example
	}
	return ""
}

func (m *Problem) GetHintAndLimit() string {
	if m != nil {
		return m.HintAndLimit
	}
	return ""
}

func (m *Problem) GetPublicizerId() uint64 {
	if m != nil {
		return m.PublicizerId
	}
	return 0
}

func (m *Problem) GetFileIoInputName() string {
	if m != nil {
		return m.FileIoInputName
	}
	return ""
}

func (m *Problem) GetFileIoOutputName() string {
	if m != nil {
		return m.FileIoOutputName
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateProblemRequest)(nil), "CreateProblemRequest")
	proto.RegisterType((*CreateProblemResponse)(nil), "CreateProblemResponse")
	proto.RegisterType((*FetechProblemRequest)(nil), "FetechProblemRequest")
	proto.RegisterType((*FetchProblemResponse)(nil), "FetchProblemResponse")
	proto.RegisterType((*Problem)(nil), "Problem")
}

func init() {
	proto.RegisterFile("problems.proto", fileDescriptor_11c986fb2f668273)
}

var fileDescriptor_11c986fb2f668273 = []byte{
	// 422 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x93, 0x4f, 0xab, 0xd3, 0x40,
	0x10, 0xc0, 0xa9, 0x7d, 0x6d, 0xda, 0x69, 0x5a, 0x1f, 0x6b, 0x2b, 0x4b, 0x41, 0xac, 0x7d, 0x1e,
	0x0a, 0x62, 0x0e, 0xf5, 0x22, 0x22, 0x82, 0x0a, 0x85, 0x82, 0xa8, 0xd4, 0x9b, 0x97, 0x90, 0x36,
	0xf3, 0x78, 0x0b, 0xd9, 0xec, 0x9a, 0x4c, 0x40, 0xfd, 0x04, 0x7e, 0x0a, 0x3f, 0xab, 0xec, 0xec,
	0x06, 0xe3, 0x7b, 0x3d, 0x78, 0x6a, 0xe7, 0x37, 0xbf, 0xf9, 0x13, 0x32, 0x81, 0x99, 0xad, 0xcc,
	0xb1, 0x40, 0x5d, 0x27, 0xb6, 0x32, 0x64, 0x96, 0x71, 0x4d, 0x19, 0x35, 0x21, 0x5a, 0xbf, 0x82,
	0xf9, 0xfb, 0x0a, 0x33, 0xc2, 0xcf, 0xde, 0x3a, 0xe0, 0xb7, 0x06, 0x6b, 0x12, 0x6b, 0x88, 0x42,
	0x9d, 0xec, 0xad, 0x7a, 0x9b, 0xc9, 0x76, 0x94, 0xb4, 0x46, 0x9b, 0x58, 0xbf, 0x84, 0xc5, 0xad,
	0xda, 0xda, 0x9a, 0xb2, 0x46, 0xf1, 0x18, 0x86, 0x7e, 0x08, 0xd7, 0xce, 0xb6, 0x51, 0xf2, 0x85,
	0xc3, 0x43, 0xc0, 0xeb, 0x0d, 0xcc, 0x77, 0x48, 0x78, 0xba, 0xb9, 0x35, 0xf5, 0x12, 0xfa, 0x56,
	0xe5, 0x5c, 0x75, 0x71, 0x70, 0x7f, 0xdd, 0x7e, 0x3b, 0xa4, 0x8e, 0x18, 0x46, 0xfc, 0xcf, 0x7e,
	0xbf, 0xfb, 0x10, 0x05, 0x78, 0xb7, 0xb3, 0x98, 0xc3, 0x80, 0x14, 0x15, 0x28, 0xef, 0xad, 0x7a,
	0x9b, 0xf1, 0xc1, 0x07, 0xe2, 0x11, 0x00, 0x29, 0x8d, 0x69, 0xa1, 0xb4, 0x22, 0xd9, 0x67, 0x7d,
	0xec, 0xc8, 0x07, 0x07, 0xc4, 0x13, 0x88, 0x35, 0x6a, 0x53, 0xfd, 0x08, 0xc2, 0x05, 0x0b, 0x13,
	0xcf, 0xbc, 0xb2, 0x82, 0x49, 0x8e, 0xf5, 0xa9, 0x52, 0x96, 0x94, 0x29, 0xe5, 0x80, 0xbb, 0x77,
	0x91, 0x6b, 0xa2, 0x4a, 0xdb, 0x50, 0x7a, 0x6d, 0x2a, 0x9d, 0x91, 0x1c, 0x7a, 0x85, 0xd9, 0x8e,
	0x91, 0xb8, 0x82, 0xa9, 0x69, 0xa8, 0xe3, 0x44, 0xec, 0xc4, 0x1e, 0x06, 0x49, 0x42, 0x84, 0xdf,
	0x33, 0x6d, 0x0b, 0x94, 0x23, 0x4e, 0xb7, 0xa1, 0x78, 0x0a, 0xb3, 0x1b, 0x55, 0x52, 0x9a, 0x95,
	0x79, 0x58, 0x74, 0xec, 0xeb, 0x1d, 0x7d, 0x5b, 0xe6, 0x7e, 0xd3, 0x2b, 0x98, 0xda, 0xe6, 0x58,
	0xa8, 0x93, 0xfa, 0x89, 0x55, 0xaa, 0x72, 0x09, 0xfc, 0x34, 0xf1, 0x5f, 0xb8, 0xcf, 0xc5, 0x33,
	0x10, 0xd7, 0xaa, 0xc0, 0x54, 0x99, 0xd4, 0x2f, 0x5d, 0x66, 0x1a, 0xe5, 0x84, 0xdb, 0xdd, 0x77,
	0x99, 0xbd, 0xd9, 0x3b, 0xfe, 0x31, 0xd3, 0x28, 0x9e, 0xc3, 0x83, 0x56, 0x0e, 0xeb, 0xb3, 0x1d,
	0xb3, 0x7d, 0xe9, 0xed, 0x4f, 0x9c, 0x70, 0xfa, 0xf6, 0x57, 0x0f, 0x46, 0xe1, 0x05, 0xd5, 0xe2,
	0x0d, 0x4c, 0xff, 0xb9, 0x26, 0xb1, 0x48, 0xce, 0x5d, 0xe6, 0xf2, 0x61, 0x72, 0xfe, 0xe8, 0x5e,
	0x43, 0xdc, 0xbd, 0x14, 0xb1, 0x48, 0xce, 0x9d, 0xd8, 0x92, 0xf1, 0x9d, 0x7b, 0x7a, 0x17, 0x7d,
	0x1d, 0xf0, 0x07, 0x71, 0x1c, 0xf2, 0xcf, 0x8b, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x12, 0x26,
	0x31, 0x1d, 0x37, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ProblemsClient is the client API for Problems service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProblemsClient interface {
	CreateProblem(ctx context.Context, in *CreateProblemRequest, opts ...grpc.CallOption) (*CreateProblemResponse, error)
	FetchProblem(ctx context.Context, in *FetechProblemRequest, opts ...grpc.CallOption) (*FetchProblemResponse, error)
}

type problemsClient struct {
	cc grpc.ClientConnInterface
}

func NewProblemsClient(cc grpc.ClientConnInterface) ProblemsClient {
	return &problemsClient{cc}
}

func (c *problemsClient) CreateProblem(ctx context.Context, in *CreateProblemRequest, opts ...grpc.CallOption) (*CreateProblemResponse, error) {
	out := new(CreateProblemResponse)
	err := c.cc.Invoke(ctx, "/Problems/CreateProblem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *problemsClient) FetchProblem(ctx context.Context, in *FetechProblemRequest, opts ...grpc.CallOption) (*FetchProblemResponse, error) {
	out := new(FetchProblemResponse)
	err := c.cc.Invoke(ctx, "/Problems/FetchProblem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProblemsServer is the server API for Problems service.
type ProblemsServer interface {
	CreateProblem(context.Context, *CreateProblemRequest) (*CreateProblemResponse, error)
	FetchProblem(context.Context, *FetechProblemRequest) (*FetchProblemResponse, error)
}

// UnimplementedProblemsServer can be embedded to have forward compatible implementations.
type UnimplementedProblemsServer struct {
}

func (*UnimplementedProblemsServer) CreateProblem(ctx context.Context, req *CreateProblemRequest) (*CreateProblemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateProblem not implemented")
}
func (*UnimplementedProblemsServer) FetchProblem(ctx context.Context, req *FetechProblemRequest) (*FetchProblemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchProblem not implemented")
}

func RegisterProblemsServer(s *grpc.Server, srv ProblemsServer) {
	s.RegisterService(&_Problems_serviceDesc, srv)
}

func _Problems_CreateProblem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProblemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProblemsServer).CreateProblem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Problems/CreateProblem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProblemsServer).CreateProblem(ctx, req.(*CreateProblemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Problems_FetchProblem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetechProblemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProblemsServer).FetchProblem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Problems/FetchProblem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProblemsServer).FetchProblem(ctx, req.(*FetechProblemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Problems_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Problems",
	HandlerType: (*ProblemsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateProblem",
			Handler:    _Problems_CreateProblem_Handler,
		},
		{
			MethodName: "FetchProblem",
			Handler:    _Problems_FetchProblem_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "problems.proto",
}
