// Code generated by mockery v1.1.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// FileService is an autogenerated mock type for the FileService type
type FileService struct {
	mock.Mock
}

// CreateDirectory provides a mock function with given fields: fileSpace, directory
func (_m *FileService) CreateDirectory(fileSpace string, directory string) error {
	ret := _m.Called(fileSpace, directory)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(fileSpace, directory)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateFile provides a mock function with given fields: fileSpace, fileName, data
func (_m *FileService) CreateFile(fileSpace string, fileName string, data []byte) error {
	ret := _m.Called(fileSpace, fileName, data)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, []byte) error); ok {
		r0 = rf(fileSpace, fileName, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateFileSpace provides a mock function with given fields: fileSpace
func (_m *FileService) CreateFileSpace(fileSpace string) error {
	ret := _m.Called(fileSpace)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(fileSpace)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
