// Code generated by mockery v1.1.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// JudgementService is an autogenerated mock type for the JudgementService type
type JudgementService struct {
	mock.Mock
}

// List provides a mock function with given fields:
func (_m *JudgementService) List() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
