// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// JudgementService is an autogenerated mock type for the JudgementService type
type JudgementService struct {
	mock.Mock
}

// Create provides a mock function with given fields: submissionId, publicSpace, privateSpace, userSpace
func (_m *JudgementService) Create(submissionId uint64, publicSpace string, privateSpace string, userSpace string) error {
	ret := _m.Called(submissionId, publicSpace, privateSpace, userSpace)

	var r0 error
	if rf, ok := ret.Get(0).(func(uint64, string, string, string) error); ok {
		r0 = rf(submissionId, publicSpace, privateSpace, userSpace)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// List provides a mock function with given fields:
func (_m *JudgementService) List() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
