// Code generated by mockery v1.1.2. DO NOT EDIT.

package mocks

import (
	repositories "github.com/infinity-oj/server/internal/app/judgements/repositories"
	mock "github.com/stretchr/testify/mock"
)

// JudgementsRepository is an autogenerated mock type for the JudgementsRepository type
type JudgementsRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: submissionId, publicSpace, privateSpace, userSpace, testCase
func (_m *JudgementsRepository) Create(submissionId uint64, publicSpace string, privateSpace string, userSpace string, testCase string) error {
	ret := _m.Called(submissionId, publicSpace, privateSpace, userSpace, testCase)

	var r0 error
	if rf, ok := ret.Get(0).(func(uint64, string, string, string, string) error); ok {
		r0 = rf(submissionId, publicSpace, privateSpace, userSpace, testCase)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Fetch provides a mock function with given fields:
func (_m *JudgementsRepository) Fetch() *repositories.Judgement {
	ret := _m.Called()

	var r0 *repositories.Judgement
	if rf, ok := ret.Get(0).(func() *repositories.Judgement); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repositories.Judgement)
		}
	}

	return r0
}

// List provides a mock function with given fields:
func (_m *JudgementsRepository) List() {
	_m.Called()
}
