// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	models "github.com/infinity-oj/server/internal/pkg/models"
	mock "github.com/stretchr/testify/mock"
)

// ProblemService is an autogenerated mock type for the ProblemService type
type ProblemService struct {
	mock.Mock
}

// CreateProblem provides a mock function with given fields: title, locale
func (_m *ProblemService) CreateProblem(title string, locale string) (*models.Page, error) {
	ret := _m.Called(title, locale)

	var r0 *models.Page
	if rf, ok := ret.Get(0).(func(string, string) *models.Page); ok {
		r0 = rf(title, locale)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Page)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(title, locale)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
