// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// SubmissionService is an autogenerated mock type for the SubmissionService type
type SubmissionService struct {
	mock.Mock
}

// Create provides a mock function with given fields: submitterId, problemId, userSpace
func (_m *SubmissionService) Create(submitterId uint64, problemId string, userSpace string) error {
	ret := _m.Called(submitterId, problemId, userSpace)

	var r0 error
	if rf, ok := ret.Get(0).(func(uint64, string, string) error); ok {
		r0 = rf(submitterId, problemId, userSpace)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
