// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	models "github.com/infinity-oj/server/internal/pkg/models"
	mock "github.com/stretchr/testify/mock"
)

// SubmissionsService is an autogenerated mock type for the SubmissionsService type
type SubmissionsService struct {
	mock.Mock
}

// Create provides a mock function with given fields: submitterID, problemID, userSpace
func (_m *SubmissionsService) Create(submitterID uint64, problemID string, userSpace string) (*models.Submission, error) {
	ret := _m.Called(submitterID, problemID, userSpace)

	var r0 *models.Submission
	if rf, ok := ret.Get(0).(func(uint64, string, string) *models.Submission); ok {
		r0 = rf(submitterID, problemID, userSpace)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Submission)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uint64, string, string) error); ok {
		r1 = rf(submitterID, problemID, userSpace)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeliverJudgement provides a mock function with given fields: submissionId
func (_m *SubmissionsService) DeliverJudgement(submissionId string) error {
	ret := _m.Called(submissionId)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(submissionId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
