// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	models "github.com/infinity-oj/server/internal/pkg/models"
	mock "github.com/stretchr/testify/mock"
)

// UserService is an autogenerated mock type for the UserService type
type UserService struct {
	mock.Mock
}

// Create provides a mock function with given fields: username, password, email
func (_m *UserService) Create(username string, password string, email string) (*models.User, error) {
	ret := _m.Called(username, password, email)

	var r0 *models.User
	if rf, ok := ret.Get(0).(func(string, string, string) *models.User); ok {
		r0 = rf(username, password, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string, string) error); ok {
		r1 = rf(username, password, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
